// <auto-generated />
namespace Sam.ToolStock.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Seeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seeding));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141434589_Seeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
