//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sam.ToolStock.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All departments.
        /// </summary>
        public static string AllDepartments {
            get {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All stocks.
        /// </summary>
        public static string AllStocks {
            get {
                return ResourceManager.GetString("AllStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        public static string BackToMainPage {
            get {
                return ResourceManager.GetString("BackToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a department.
        /// </summary>
        public static string ChooseDepartment {
            get {
                return ResourceManager.GetString("ChooseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose lang.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a stock.
        /// </summary>
        public static string ChooseStock {
            get {
                return ResourceManager.GetString("ChooseStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a department.
        /// </summary>
        public static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a stock.
        /// </summary>
        public static string CreateStock {
            get {
                return ResourceManager.GetString("CreateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of login.
        /// </summary>
        public static string ErrorOfLogin {
            get {
                return ResourceManager.GetString("ErrorOfLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail field is not a valid e-mail address..
        /// </summary>
        public static string LoginEmailIsNotValid {
            get {
                return ResourceManager.GetString("LoginEmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail field is required..
        /// </summary>
        public static string LoginEmailIsRequired {
            get {
                return ResourceManager.GetString("LoginEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string LoginInvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("LoginInvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Password&apos; must be at least 6 characters..
        /// </summary>
        public static string LoginMinLengthPassword {
            get {
                return ResourceManager.GetString("LoginMinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in or register.
        /// </summary>
        public static string LogInOrRegisterRequest {
            get {
                return ResourceManager.GetString("LogInOrRegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string LoginPasswordIsRequired {
            get {
                return ResourceManager.GetString("LoginPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} was updated successfully!.
        /// </summary>
        public static string ModalPageMessageUpdate {
            get {
                return ResourceManager.GetString("ModalPageMessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Confirm Password&apos; must be equal to &apos;Password&apos;..
        /// </summary>
        public static string RegisterConfirmPasswordEqualPassword {
            get {
                return ResourceManager.GetString("RegisterConfirmPasswordEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Name&apos; must be 60 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthName {
            get {
                return ResourceManager.GetString("RegisterMaxLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Patronymic&apos; must be 70 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthPatronymic {
            get {
                return ResourceManager.GetString("RegisterMaxLengthPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Phone&apos; must be 20 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthPhone {
            get {
                return ResourceManager.GetString("RegisterMaxLengthPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Surname&apos; must be 80 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthSurname {
            get {
                return ResourceManager.GetString("RegisterMaxLengthSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required..
        /// </summary>
        public static string RegisterNameIsRequired {
            get {
                return ResourceManager.GetString("RegisterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Surname field is required..
        /// </summary>
        public static string RegisterSurnameIsRequired {
            get {
                return ResourceManager.GetString("RegisterSurnameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to.
        /// </summary>
        public static string ReturnTo {
            get {
                return ResourceManager.GetString("ReturnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Editing&lt;/strong&gt; User.
        /// </summary>
        public static string ShowUserMenuTitle {
            get {
                return ResourceManager.GetString("ShowUserMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the users page.
        /// </summary>
        public static string UsersPage {
            get {
                return ResourceManager.GetString("UsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Table.
        /// </summary>
        public static string UserTable {
            get {
                return ResourceManager.GetString("UserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your department.
        /// </summary>
        public static string YourDepartment {
            get {
                return ResourceManager.GetString("YourDepartment", resourceCulture);
            }
        }
    }
}
