//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sam.ToolStock.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All departments.
        /// </summary>
        public static string AllDepartments {
            get {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all departments page.
        /// </summary>
        public static string AllDepartmentsPage {
            get {
                return ResourceManager.GetString("AllDepartmentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All stocks.
        /// </summary>
        public static string AllStocks {
            get {
                return ResourceManager.GetString("AllStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all stocks page.
        /// </summary>
        public static string AllStocksPage {
            get {
                return ResourceManager.GetString("AllStocksPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tools.
        /// </summary>
        public static string AllTools {
            get {
                return ResourceManager.GetString("AllTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the all tool types page.
        /// </summary>
        public static string AllToolTypePage {
            get {
                return ResourceManager.GetString("AllToolTypePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tool types.
        /// </summary>
        public static string AllToolTypes {
            get {
                return ResourceManager.GetString("AllToolTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of elements.
        /// </summary>
        public static string AmountOfElements {
            get {
                return ResourceManager.GetString("AmountOfElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main page.
        /// </summary>
        public static string BackToMainPage {
            get {
                return ResourceManager.GetString("BackToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed tools.
        /// </summary>
        public static string BorrowedTools {
            get {
                return ResourceManager.GetString("BorrowedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing department.
        /// </summary>
        public static string ChangingDepartment {
            get {
                return ResourceManager.GetString("ChangingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a department.
        /// </summary>
        public static string ChooseDepartment {
            get {
                return ResourceManager.GetString("ChooseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a manufacturer.
        /// </summary>
        public static string ChooseManufacturer {
            get {
                return ResourceManager.GetString("ChooseManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a stock.
        /// </summary>
        public static string ChooseStock {
            get {
                return ResourceManager.GetString("ChooseStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a tool type.
        /// </summary>
        public static string ChooseToolType {
            get {
                return ResourceManager.GetString("ChooseToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user.
        /// </summary>
        public static string ChooseUser {
            get {
                return ResourceManager.GetString("ChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a department.
        /// </summary>
        public static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the create department page.
        /// </summary>
        public static string CreateDepartmentPage {
            get {
                return ResourceManager.GetString("CreateDepartmentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new department.
        /// </summary>
        public static string CreateNewDepartment {
            get {
                return ResourceManager.GetString("CreateNewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new stock.
        /// </summary>
        public static string CreateNewStock {
            get {
                return ResourceManager.GetString("CreateNewStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new tool.
        /// </summary>
        public static string CreateNewTool {
            get {
                return ResourceManager.GetString("CreateNewTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new tool type.
        /// </summary>
        public static string CreateNewToolType {
            get {
                return ResourceManager.GetString("CreateNewToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a stock.
        /// </summary>
        public static string CreateStock {
            get {
                return ResourceManager.GetString("CreateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the create stock page.
        /// </summary>
        public static string CreateStockPage {
            get {
                return ResourceManager.GetString("CreateStockPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a tool.
        /// </summary>
        public static string CreateTool {
            get {
                return ResourceManager.GetString("CreateTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the create tool page.
        /// </summary>
        public static string CreateToolPage {
            get {
                return ResourceManager.GetString("CreateToolPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tools.
        /// </summary>
        public static string CreateTools {
            get {
                return ResourceManager.GetString("CreateTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a tool type.
        /// </summary>
        public static string CreateToolType {
            get {
                return ResourceManager.GetString("CreateToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the create tool type page.
        /// </summary>
        public static string CreateToolTypePage {
            get {
                return ResourceManager.GetString("CreateToolTypePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department creating.
        /// </summary>
        public static string DepartmentCreating {
            get {
                return ResourceManager.GetString("DepartmentCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A department for new stock.
        /// </summary>
        public static string DepartmentForNewStock {
            get {
                return ResourceManager.GetString("DepartmentForNewStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department reassigning.
        /// </summary>
        public static string DepartmentReassigning {
            get {
                return ResourceManager.GetString("DepartmentReassigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Table.
        /// </summary>
        public static string DepartmentTable {
            get {
                return ResourceManager.GetString("DepartmentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of login.
        /// </summary>
        public static string ErrorOfLogin {
            get {
                return ResourceManager.GetString("ErrorOfLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give in for repair.
        /// </summary>
        public static string GiveInForRepair {
            get {
                return ResourceManager.GetString("GiveInForRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the status is IssuedToUser, you must assign a user.
        /// </summary>
        public static string IfStatusIsIssuedToUserYouMustAssignUser {
            get {
                return ResourceManager.GetString("IfStatusIsIssuedToUserYouMustAssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to assign a user, you must set the status to IssuedToUser.
        /// </summary>
        public static string InOrderToAssignUserYouMustSetStatusToIssuedToUser {
            get {
                return ResourceManager.GetString("InOrderToAssignUserYouMustSetStatusToIssuedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In The Stock.
        /// </summary>
        public static string InTheStock {
            get {
                return ResourceManager.GetString("InTheStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued To A User.
        /// </summary>
        public static string IssuedToUser {
            get {
                return ResourceManager.GetString("IssuedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue the tool.
        /// </summary>
        public static string IssueTool {
            get {
                return ResourceManager.GetString("IssueTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail field is not a valid e-mail address..
        /// </summary>
        public static string LoginEmailIsNotValid {
            get {
                return ResourceManager.GetString("LoginEmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail field is required..
        /// </summary>
        public static string LoginEmailIsRequired {
            get {
                return ResourceManager.GetString("LoginEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string LoginInvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("LoginInvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Password&apos; must be at least 6 characters..
        /// </summary>
        public static string LoginMinLengthPassword {
            get {
                return ResourceManager.GetString("LoginMinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in or register.
        /// </summary>
        public static string LogInOrRegisterRequest {
            get {
                return ResourceManager.GetString("LogInOrRegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string LoginPasswordIsRequired {
            get {
                return ResourceManager.GetString("LoginPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} was changed successfully!.
        /// </summary>
        public static string ModalPageMessageChange {
            get {
                return ResourceManager.GetString("ModalPageMessageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &quot;{1}&quot; was created successfully!.
        /// </summary>
        public static string ModalPageMessageCreate {
            get {
                return ResourceManager.GetString("ModalPageMessageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}&quot;{1}&quot; was deleted successfully!.
        /// </summary>
        public static string ModalPageMessageDelete {
            get {
                return ResourceManager.GetString("ModalPageMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &quot;{1}&quot; was restored successfully!.
        /// </summary>
        public static string ModalPageMessageRestore {
            get {
                return ResourceManager.GetString("ModalPageMessageRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} was updated successfully!.
        /// </summary>
        public static string ModalPageMessageUpdate {
            get {
                return ResourceManager.GetString("ModalPageMessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to another stock.
        /// </summary>
        public static string MoveToStock {
            get {
                return ResourceManager.GetString("MoveToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New department for stocks.
        /// </summary>
        public static string NewDepartmentForStocks {
            get {
                return ResourceManager.GetString("NewDepartmentForStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New department for users.
        /// </summary>
        public static string NewDepartmentForUsers {
            get {
                return ResourceManager.GetString("NewDepartmentForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New stock for tools.
        /// </summary>
        public static string NewStockForTools {
            get {
                return ResourceManager.GetString("NewStockForTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New stock for users.
        /// </summary>
        public static string NewStockForUsers {
            get {
                return ResourceManager.GetString("NewStockForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a complex password.
        /// </summary>
        public static string PleaseEnterComplexPassword {
            get {
                return ResourceManager.GetString("PleaseEnterComplexPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password again.
        /// </summary>
        public static string PleaseEnterPasswordAgain {
            get {
                return ResourceManager.GetString("PleaseEnterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password.
        /// </summary>
        public static string PleaseEnterYourOldPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassigning Users and Stocks from &lt;strong&gt;the deleting department&lt;/strong&gt;.
        /// </summary>
        public static string ReassigningUsersAndStocksMessage {
            get {
                return ResourceManager.GetString("ReassigningUsersAndStocksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassigning Users and Tools from &lt;strong&gt;the deleting stock&lt;/strong&gt;.
        /// </summary>
        public static string ReassigningUsersAndToolssMessage {
            get {
                return ResourceManager.GetString("ReassigningUsersAndToolssMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Confirm Password&apos; must be equal to &apos;Password&apos;..
        /// </summary>
        public static string RegisterConfirmPasswordEqualPassword {
            get {
                return ResourceManager.GetString("RegisterConfirmPasswordEqualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Name&apos; must be 60 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthName {
            get {
                return ResourceManager.GetString("RegisterMaxLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Patronymic&apos; must be 70 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthPatronymic {
            get {
                return ResourceManager.GetString("RegisterMaxLengthPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Phone&apos; must be 20 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthPhone {
            get {
                return ResourceManager.GetString("RegisterMaxLengthPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &apos;Surname&apos; must be 80 characters or fewer..
        /// </summary>
        public static string RegisterMaxLengthSurname {
            get {
                return ResourceManager.GetString("RegisterMaxLengthSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required..
        /// </summary>
        public static string RegisterNameIsRequired {
            get {
                return ResourceManager.GetString("RegisterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Surname field is required..
        /// </summary>
        public static string RegisterSurnameIsRequired {
            get {
                return ResourceManager.GetString("RegisterSurnameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename tool type.
        /// </summary>
        public static string RenameToolType {
            get {
                return ResourceManager.GetString("RenameToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the tool from repair.
        /// </summary>
        public static string ReturnFromRepair {
            get {
                return ResourceManager.GetString("ReturnFromRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the tool from a user.
        /// </summary>
        public static string ReturnFromUser {
            get {
                return ResourceManager.GetString("ReturnFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to.
        /// </summary>
        public static string ReturnTo {
            get {
                return ResourceManager.GetString("ReturnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return tool.
        /// </summary>
        public static string ReturnTool {
            get {
                return ResourceManager.GetString("ReturnTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the setting page.
        /// </summary>
        public static string SettingPage {
            get {
                return ResourceManager.GetString("SettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Editing&lt;/strong&gt; User.
        /// </summary>
        public static string ShowUserMenuTitle {
            get {
                return ResourceManager.GetString("ShowUserMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock amount.
        /// </summary>
        public static string StockAmount {
            get {
                return ResourceManager.GetString("StockAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock creating.
        /// </summary>
        public static string StockCreating {
            get {
                return ResourceManager.GetString("StockCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock reassigning.
        /// </summary>
        public static string StockReassigning {
            get {
                return ResourceManager.GetString("StockReassigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system already has a tool with that name. Its manufacturer is {0}..
        /// </summary>
        public static string SystemAlreadyHasToolWithThatNameManufacturer {
            get {
                return ResourceManager.GetString("SystemAlreadyHasToolWithThatNameManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system already has a tool with that name. Its type is {0}..
        /// </summary>
        public static string SystemAlreadyHasToolWithThatNameToolType {
            get {
                return ResourceManager.GetString("SystemAlreadyHasToolWithThatNameToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This Page Could Not Be Found.
        /// </summary>
        public static string ThisPageCouldNotBeFound {
            get {
                return ResourceManager.GetString("ThisPageCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Actions.
        /// </summary>
        public static string ToolActions {
            get {
                return ResourceManager.GetString("ToolActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool amount.
        /// </summary>
        public static string ToolAmount {
            get {
                return ResourceManager.GetString("ToolAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool type.
        /// </summary>
        public static string ToolType {
            get {
                return ResourceManager.GetString("ToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool type creating.
        /// </summary>
        public static string ToolTypeCreating {
            get {
                return ResourceManager.GetString("ToolTypeCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool types.
        /// </summary>
        public static string ToolTypes {
            get {
                return ResourceManager.GetString("ToolTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool type table.
        /// </summary>
        public static string ToolTypeTable {
            get {
                return ResourceManager.GetString("ToolTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Repair.
        /// </summary>
        public static string UnderRepair {
            get {
                return ResourceManager.GetString("UnderRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update department.
        /// </summary>
        public static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update stock.
        /// </summary>
        public static string UpdateStock {
            get {
                return ResourceManager.GetString("UpdateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User amount.
        /// </summary>
        public static string UserAmount {
            get {
                return ResourceManager.GetString("UserAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user profile page.
        /// </summary>
        public static string UserProfilePage {
            get {
                return ResourceManager.GetString("UserProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the users page.
        /// </summary>
        public static string UsersPage {
            get {
                return ResourceManager.GetString("UsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Table.
        /// </summary>
        public static string UserTable {
            get {
                return ResourceManager.GetString("UserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write off.
        /// </summary>
        public static string WriteOff {
            get {
                return ResourceManager.GetString("WriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Off.
        /// </summary>
        public static string WrittenOff {
            get {
                return ResourceManager.GetString("WrittenOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose any department.
        /// </summary>
        public static string YouDidNotChooseDepartment {
            get {
                return ResourceManager.GetString("YouDidNotChooseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose any stock.
        /// </summary>
        public static string YouDidNotChooseStock {
            get {
                return ResourceManager.GetString("YouDidNotChooseStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose any tool type.
        /// </summary>
        public static string YouDidNotChooseToolType {
            get {
                return ResourceManager.GetString("YouDidNotChooseToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose any user.
        /// </summary>
        public static string YouDidNotChooseUser {
            get {
                return ResourceManager.GetString("YouDidNotChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t reassign stocks.
        /// </summary>
        public static string YouDidNotReassignStocks {
            get {
                return ResourceManager.GetString("YouDidNotReassignStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t reassign tools.
        /// </summary>
        public static string YouDidNotReassignTools {
            get {
                return ResourceManager.GetString("YouDidNotReassignTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t reassign users.
        /// </summary>
        public static string YouDidNotReassignUsers {
            get {
                return ResourceManager.GetString("YouDidNotReassignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked..
        /// </summary>
        public static string YourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("YourAccountHasBeenBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your department.
        /// </summary>
        public static string YourDepartment {
            get {
                return ResourceManager.GetString("YourDepartment", resourceCulture);
            }
        }
    }
}
